TomocaMoviesWebsite/TomocaMoviesWebsite/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TomocaMoviesWebsite.Models;

namespace TomocaMoviesWebsite.Controllers
{
    public class UsersController : Controller
    {
        // GET: Users
        TomocaMoviesDataContext db = new TomocaMoviesDataContext();
        public static string FilterSql(string s)
        {
            if (string.IsNullOrEmpty(s)) return string.Empty;
            s = s.Trim().ToLower();
            s = s.Replace("=", "");
            s = s.Replace("'", "");
            s = s.Replace(";", "");
            s = s.Replace(" or ", "");
            s = s.Replace("select", "");
            s = s.Replace("update", "");
            s = s.Replace("insert", "");
            s = s.Replace("delete", "");
            s = s.Replace("declare", "");
            s = s.Replace("exec", "");
            s = s.Replace("drop", "");
            s = s.Replace("create", "");
            s = s.Replace("%", "");
            s = s.Replace("--", "");
            return s;
        }
        public ActionResult Login(FormCollection collection)
        {
            var una = collection["Username"];
            var pwa = collection["Password"];
            var un = FilterSql(una);
            var pw = FilterSql(pwa);
            if (String.IsNullOrEmpty(un))
                ViewData["Loi"] = "Bạn phải nhập tên đăng nhập";
            else if (String.IsNullOrEmpty(pw))
            {
                ViewData["Loi1"] = "Bạn phải nhập mật khẩu";
            }
            else
            {
                User tk = db.Users.SingleOrDefault(n => n.Username.Equals(un) && n.Password.Equals(pw));
                if (tk != null)
                {
                    if (tk.Permission == true)//Admin
                    {
                        @Session["Username"] = tk.Username;
                        @Session["Permission"] = 1;
                        ViewBag.ThongBao = "Đăng nhập thành công admin";
                        return RedirectToAction("Home", "Admin");
                    }
                    if (tk.Permission == false || tk.Permission == null)
                    {
                        @Session["Username"] = tk.Username;
                        @Session["Permission"] = null;
                        ViewBag.ThongBao = "Đăng nhập thành công";
                        return RedirectToAction("Index", "Tomoca");
                    }
                }
                else
                {
                    ViewData["Loi2"] = "Tên đăng nhâp hoặc mật khẩu không đúng";
                }
            }
            return View();
        }
        public ActionResult Signup()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Signup(User tk, FormCollection coll)
        {
            var tendn = coll["TenDN"];
            var mk = coll["MatKhau"];
            var mknhaplai = coll["MatKhauNhapLai"];
            var fn = coll["TenDau"];
            var ln = coll["TenCuoi"];
            var em = coll["email"];
            var ph = coll["sodienthoai"];
            //var taikhoan = from t in data.TaiKhoans where t.TenDN.Equals(tendn) select t.TenDN;
            var taikhoan = db.Users.ToList();
            int kt = 0;
            int kt2 = 0;
            var ktem = db.Users.Where(a => a.Email == em);
            foreach (var item in taikhoan)
            {
                if (item.Username == tendn)
                    kt = 1;
                if (item.Phone == ph)
                    kt2 = 1;
            }
            if (String.IsNullOrEmpty(tendn))
                ViewData["Loi"] = "Tên đăng nhập không được để chống";
            else if (String.IsNullOrEmpty(mk))
                ViewData["Loi1"] = "Mật khẩu không được để chống";
            else if (String.IsNullOrEmpty(em))
                ViewData["Loi2"] = "Vui lòng nhập Email";
            else if (String.IsNullOrEmpty(ph))
                ViewData["Loi3"] = "Vui lòng nhập số điện thoại";
            else if (kt == 1)
            {
                ViewData["Loi2"] = "Đã có tài khoản này";
            }
            else if (ktem.Count() != 0)
            {
                ViewData["Loi2e"] = "Email đã được sử dụng";
            }
            else if (kt2 == 1)
            {
                ViewData["Loi3e"] = "Số điện thoại đã được sử dụng";
            }
            else if (mk != mknhaplai)
            {
                ViewData["Loi12"] = "Mật khẩu nhập lại không đúng";
            }
            else
            {
                tk.Username = tendn;
                tk.Password = mk;
                tk.FirstName = fn;
                tk.LastName = ln;
                tk.Email = em;
                tk.Phone = ph;
                db.Users.InsertOnSubmit(tk);
                db.SubmitChanges();
                return RedirectToAction("signupfinish");
            }
            return View();
        }
        public ActionResult signupfinish()
        {
            return View();
        }
        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Index", "Tomoca");
        }
        public ActionResult profile()
        {
            return View();
        }
    }
}

TomocaMoviesWebsite/TomocaMoviesWebsite/Controllers/adminmanagerController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TomocaMoviesWebsite.Models;

namespace TomocaMoviesWebsite.Controllers
{
    public class adminmanagerController : BaseController
    {
        // GET: adminmanager
        TomocaMoviesDataContext data = new TomocaMoviesDataContext();
        public ActionResult users()
        {
            var tk = data.Users.ToList();
            return View(tk);
        }
        public ActionResult delete(int id)
        {
            User tk = data.Users.SingleOrDefault(n => n.UserID == id);
            if (tk == null)
            {
                Response.SubStatusCode = 404;
                return null;
            }
            data.Users.DeleteOnSubmit(tk);
            data.SubmitChanges();
            return RedirectToAction("users");
        }
        //Thêm tài khoản
        public ActionResult add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult add(User tk, FormCollection coll)
        {
            var tendn = coll["TenDN"];
            var mk = coll["MatKhau"];
            var mknhaplai = coll["MatKhauNhapLai"];
            var fn = coll["TenDau"];
            var ln = coll["TenCuoi"];
            var em = coll["email"];
            var ph = coll["sodienthoai"];
            //var taikhoan = from t in data.TaiKhoans where t.TenDN.Equals(tendn) select t.TenDN;
            var taikhoan = data.Users.ToList();
            int kt = 0;
            int kt2 = 0;
            var ktem = data.Users.Where(a => a.Email == em);
            foreach (var item in taikhoan)
            {
                if (item.Username == tendn)
                    kt = 1;
                if (item.Phone == ph)
                    kt2 = 1;
            }
            if (String.IsNullOrEmpty(tendn))
                ViewData["Loi"] = "Tên đăng nhập không được để chống";
            else if (String.IsNullOrEmpty(mk))
                ViewData["Loi1"] = "Mật khẩu không được để chống";
            else if (String.IsNullOrEmpty(em))
                ViewData["Loi2"] = "Vui lòng nhập Email";
            else if (String.IsNullOrEmpty(ph))
                ViewData["Loi3"] = "Vui lòng nhập số điện thoại";
            else if (kt == 1)
            {
                ViewData["Loi2"] = "Đã có tài khoản này";
            }
            else if (ktem.Count() != 0)
            {
                ViewData["Loi2e"] = "Email đã được sử dụng";
            }
            else if (kt2 == 1)
            {
                ViewData["Loi3e"] = "Số điện thoại đã được sử dụng";
            }
            else if (mk != mknhaplai)
            {
                ViewData["Loi12"] = "Mật khẩu nhập lại không đúng";
            }
            else
            {
                tk.Username = tendn;
                tk.Password = mk;
                tk.FirstName = fn;
                tk.LastName = ln;
                tk.Email = em;
                tk.Phone = ph;
                data.Users.InsertOnSubmit(tk);
                data.SubmitChanges();
                return RedirectToAction("users");
            }
            return View();
        }
        //Sửa
        public ActionResult edit(string id)
        {
            var tk = data.Users.First(n => n.UserID.ToString() == id);
            if (tk == null)
            {
                Response.SubStatusCode = 404;
                return null;
            }
            return View(tk);
        }

        [HttpPost]
        public ActionResult edit(string id, FormCollection collection)
        {
            var tk = data.Users.First(n => n.UserID.ToString() == id);
            var taikhoan = data.Users.ToList();
            var fn = collection["FirstName"];
            var ln = collection["LastName"];
            var em = collection["Email"];
            var ph = collection["Phone"];
            var matkhau = collection["Password"];
            int kt2 = 0;
            var ktem = data.Users.Where(a => a.Email == em && tk.Email != em);
            var ktph = data.Users.Where(a => a.Phone == em && tk.Phone != em);
            if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi"] = "Không được để trống";
            }
            else if (String.IsNullOrEmpty(em))
                ViewData["Loi2"] = "Vui lòng nhập Email";
            else if (String.IsNullOrEmpty(ph))
                ViewData["Loi3"] = "Vui lòng nhập số điện thoại";
            else if (ktem.Count() != 0)
            {
                ViewData["Loi2e"] = "Email đã được sử dụng";
            }
            else if (ktph.Count() != 0)
            {
                ViewData["Loi3e"] = "Số điện thoại đã được sử dụng";
            }
            else
            {
                tk.Password = matkhau;
                tk.Phone = ph;
                tk.Email = em;
                tk.FirstName = fn;
                tk.LastName = ln;
                UpdateModel(tk);
                data.SubmitChanges();
                return RedirectToAction("users");
            }
            return this.edit(id);
        }
        //phim đang chiếu
        public ActionResult phimdangchieu()
        {
            var PhimDangChieu = from tt in data.Movies
                                where tt.ComingSoon == 0
                                select tt;
            return View(PhimDangChieu);
        }
        [HttpGet]
        public ActionResult ThemPhim()
        {
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ThemPhim(IEnumerable<HttpPostedFileBase> files, Movy mv)
        {
            DateTime a = DateTime.Now;
            var tintuc = data.News.ToList();
            int count = 1;
            foreach (var item in files)
            {
                if (item.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(item.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/image/news"), fileName);
                    item.SaveAs(path);
                    if (count == 1)
                    {

                        mv.Image = "/Content/image/news/" + fileName;

                    }
                    if (count == 2)
                    {

                        mv.Banner = "/Content/image/news/" + fileName;
                    }
                }
                if (count == item.ContentLength)
                    break;
                count++;
            }
            data.Movies.InsertOnSubmit(mv);
            data.SubmitChanges();
            if(mv.ComingSoon == 1)
            {
                return RedirectToAction("phimSC");
            }
            else
            {
                return RedirectToAction("phimdangchieu");
            } 
        }
        //Them Chi Tiet DC
        public ActionResult ThemChiTiet(int id)
        {
            return View();
        }
        [HttpPost]
        public ActionResult ThemChiTiet(int id, FormCollection coll, MovieActor ma, MovieDirector md, MoviesGenre mg, ReviewOfMovie yt, YoutubeReview ytb)
        {
            var youtube = coll["Author"];
            var youtubelink = coll["Video"];
            //var actorid = data.Actors.First(a => a.Name == coll["Actor"]);
            //var drid = data.Directors.First(a => a.Name == coll["Director"]);
            //var gns = data.Genres.First(a => a.GenreName == coll["Type"]);
            var temp = 0;
            foreach(var i in data.YoutubeReviews)
            {
                if(i.YoutubeID > temp)
                {
                    temp = i.YoutubeID;
                }
            }
            int count = data.ReviewOfMovies.First(m => m.MovieID == id-1).YoutubeID;
            //
            //ma.MovieID = moviid.MovieID;
            //ma.ActorID = actorid.ActorID;
            //data.MovieActors.InsertOnSubmit(ma);
            ////
            //md.MovieID = moviid.MovieID;
            //md.DirectorID = drid.DirectorID;
            //data.MovieDirectors.InsertOnSubmit(md);
            ////
            //mg.MovieID = moviid.MovieID;
            //mg.GenreID = gns.GenreID;
            //data.MoviesGenres.InsertOnSubmit(mg);
            // Thêm Youtube Review
            ytb.Author = youtube;
            ytb.Image = "Image";
            ytb.Video = youtubelink;
            data.YoutubeReviews.InsertOnSubmit(ytb);
            // Thêm Review of Youtube
            yt.MovieID = id;
            yt.YoutubeID = temp+1;
            data.ReviewOfMovies.InsertOnSubmit(yt);
            data.SubmitChanges();
            if(data.Movies.First(m=>m.MovieID == id).ComingSoon == 1)
            {
                return RedirectToAction("phimSC");
            }
            return RedirectToAction("phimdangchieu");
        }
        // Phim sắp chiếu
        public ActionResult phimSC()
        {
            var phimSC = from tt in data.Movies
                         where tt.ComingSoon == 1 || tt.ComingSoon == null
                         select tt;
            return View(phimSC);
        }
        // Doanh thu vé
        public ActionResult datve()
        {
            var tk = from tt in data.Tickets
                         select tt;
            return View(tk);
        }
        public ActionResult chitietve(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("datve");
            }
            var chitiet = data.Tickets.Where(x => x.TicketID == id).Take(1).ToList();
            return View(chitiet);
        }
        public ActionResult XoaPhimSC(int id)
        {
            Movy dg = data.Movies.SingleOrDefault(n => n.MovieID == id);
            //ReviewOfMovie dg1 = data.ReviewOfMovies.First(n => n.MovieID == id);
            //YoutubeReview dg2 = data.YoutubeReviews.First(n => n.YoutubeID == dg1.YoutubeID);
            if (dg == null)
            {
                Response.SubStatusCode = 404;

TomocaMoviesWebsite/TomocaMoviesWebsite/Views/adminmanager/ThemChiTiet.cshtml
@using TomocaMoviesWebsite.Models
@{
    ViewBag.Title = "ThemChiTiet";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
    TomocaMoviesDataContext db = new TomocaMoviesDataContext();
    var lst = db.Genres.Where(x => x.GenreID > 0).ToList();
    var lst1 = db.Directors.Where(x => x.DirectorID > 0).ToList();
    var lst2 = db.Actors.Where(x => x.ActorID > 0).ToList();
}

@using (Html.BeginForm("ThemChiTiet", "adminmanager", FormMethod.Post))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend></legend>

        <div class="editor-field">
            <table>
                <tr>
                    <td style="width:125px"><b> Tên Diễn Viên</b></td>
                    <td>
                        <select name="Actor" class="form-control">
                            @foreach (var item in lst2)
                            {
                                <option value="@item.ActorID">@item.Name</option>
                            }
                        </select>
                        <a href="~/Admin/ThemDienVien">Thêm Diễn Viên</a>
                    </td>
                    <td style="color:red">
                        @ViewData["Loi1"]
                        @ViewData["Loi2"]
                    </td>
                </tr>
                <tr>
                    <td style="width:125px"><b>Tên Đạo Diễn</b></td>
                    <td>
                        <select name="Director" class="form-control">
                            @foreach (var item in lst1)
                            {
                                <option value="@item.DirectorID">@item.Name</option>
                            }
                        </select>
                        <a href="~/Admin/ThemDienVien">Thêm Đạo Diễn</a>
                    </td>
                    <td style="color:red">
                        @ViewData["Loi1"]
                        @ViewData["Loi2"]
                    </td>
                </tr>
                <tr>
                    <td style="width:125px"><b>Thể Loại</b></td>
                    <td>
                        <select name="Type" class="form-control">
                            @foreach (var item in lst)
                            {
                                <option value="@item.GenreID">@item.GenreName</option>
                            }
                            <a href="~/Admin/ThemDienVien">Thêm Thể Loại</a>
                        </select>
                    </td>
                    <td style="color:red">
                        @ViewData["Loi1"]
                        @ViewData["Loi2"]
                    </td>
                </tr>
                <tr>
                    <td style="width:125px"><b>Youtube Review</b><br /><b style="margin-left: 15px;">Thêm Tác Giả</b></td>
                    <td>
                        <input type="text" name="Author" id="author" class="form-control" />
                    </td>
                    <td style="color:red">
                        @ViewData["Loi1"]
                        @ViewData["Loi2"]
                    </td>
                </tr>
                <tr>
                    <td style="width:125px"><b style="margin-left: 15px;">Thêm Video</b></td>
                    <td>
                        <input type="text" name="Video" id="video" class="form-control" />
                    </td>
                    <td style="color:red">
                        @ViewData["Loi1"]
                        @ViewData["Loi2"]
                    </td>
                </tr>
            </table>
        </div>
        <p>
            <input type="submit" value="Thêm Chi Tiết" class="btn btn-success" />
        </p>
    </fieldset>
}
<div>
    @Html.ActionLink("Trở lại", "DienVien", "Admin")
</div>

TomocaMoviesWebsite/TomocaMoviesWebsite/Views/adminmanager/ThemPhim.cshtml
@model TomocaMoviesWebsite.Models.Movy

@{
    ViewBag.Title = "ThemPhim";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

<h2>ThemPhimDC</h2>

@using (Html.BeginForm("ThemPhim", "adminmanager", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Movy</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Plot, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Plot, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Plot, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReleaseYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IMDb, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IMDb, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IMDb, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tomatometer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tomatometer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tomatometer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AudienceScore, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AudienceScore, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AudienceScore, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="files" required class="form-control"/>
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Trailer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Trailer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Trailer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TimeOfFilm, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TimeOfFilm, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TimeOfFilm, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Banner, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="files" required class="form-control" />
                @Html.ValidationMessageFor(model => model.Banner, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ComingSoon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ComingSoon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ComingSoon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TomocaMoviesWebsite/TomocaMoviesWebsite/Views/adminmanager/add.cshtml
@model TomocaMoviesWebsite.Models.User

@{
    ViewBag.Title = "add";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

<h2>Thêm tài khoản</h2>
@using (Html.BeginForm("add", "adminmanager", FormMethod.Post))
{
    @Html.ValidationSummary(true)
    <div class="signup">
        <h3>Signing Up</h3>
        <form>
            <div class="grid-signup">
                <div class="signup-item-bg signup-item1 ">
                    <p>User Name</p>
                    @*<input type="text" name="username" value="" placeholder="Choose your user name">*@
                    @Html.TextBox("TenDN", null, new { @class = "forcontrol", placeholder = "Choose your user name" })
                    @ViewData["Loi2"]
                    @ViewData["Loi"]
                </div>
                <div class="signup-item-bg signup-item2">
                    <div class="fistname">
                        <p>First Name</p>
                        @Html.TextBox("TenDau", null, new { @class = "forcontrol", placeholder = "Aa" })
                        @ViewData["Loi"]
                        @*<input type="text" name="firstname" value="" placeholder="Aa">*@
                    </div>
                    <div class="lastname">
                        <p>Last Name</p>
                        @*<input type="text" name="lastname" value="" placeholder="Aa">*@
                        @Html.TextBox("TenCuoi", null, new { @class = "forcontrol", placeholder = "Aa" })
                        @ViewData["Loi12"]
                    </div>
                </div>
                <div class="signup-item-bg signup-item3">
                    <p>Password</p>
                    @*<input type="password" name="password" value="" placeholder="Enter your Tomoca password">*@
                    @Html.Password("MatKhau", null, new { @class = "forcontrol", placeholder = "Enter your Tomoca password" })
                    @ViewData["Loi1"];
                </div>
                <div class="signup-item-bg signup-item4">
                    <p>Confirm Password</p>
                    @*<input type="password" name="repassword" value="" placeholder="Re-enter your password">*@
                    @Html.Password("MatKhauNhapLai", null, new { @class = "forcontrol", placeholder = "Re-enter your password" })
                    @ViewData["Loi12"]
                </div>
                <div class="signup-item-bg signup-item5">
                    <p>Email address</p>
                    @*<input type="email" name="email" value="" placeholder="Enter your email">*@
                    @Html.TextBox("email", null, new { @class = "forcontrol", placeholder = "Enter your email" })
                    @ViewData["Loi2"]
                    @ViewData["Loi2e"]
                </div>
                <div class="signup-item-bg signup-item6">
                    <p>Phone Number</p>
                    @*<input type="number" name="phone" value="" placeholder="Enter your phone number">*@
                    @Html.TextBox("sodienthoai", null, new { @class = "forcontrol", placeholder = "Enter your phone number" })
                    @ViewData["Loi3"]
                    @ViewData["Loi3e"]
                </div>
            </div>
            <button type="submit" style="margin-top: 54px;">Finish</button><br>
            <button type="reset" style="background-color:#F0F0F0; border: 1px solid #BEBEBE; color: #5C5C5C;"><a style="color:#5C5C5C;" href="~/Users/Login">Return to login</a></button>
        </form>
    </div>
}

TomocaMoviesWebsite/TomocaMoviesWebsite/Views/adminmanager/edit.cshtml
@model TomocaMoviesWebsite.Models.User

@{
    ViewBag.Title = "edit";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}
<h2>Sửa tài khoản</h2>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend></legend>

        <div class="editor-field">
            <table>
                <tr>
                    <td>
                        <b>Tên đăng nhâp :  </b>
                    </td>
                    <td>
                        @Model.Username
                    </td>
                </tr>
                <tr>
                    <td style="width:125px"><b>Mật khẩu </b></td>
                    <td>
                        @Html.TextBoxFor(model => model.Password, new { @class = "form-control" })
                        @ViewData["Loi"]
                    </td>
                </tr>
                <tr>
                    <td style="width:125px"><b>Tên Họ </b></td>
                    <td>
                        @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control" })
                        @ViewData["Loi"]
                    </td>
                </tr>
                <tr>
                    <td style="width:125px"><b>Tên </b></td>
                    <td>
                        @Html.TextBoxFor(model => model.LastName, new { @class = "form-control" })
                        @ViewData["Loi"]
                    </td>
                </tr>
                <tr>
                    <td style="width:125px"><b>Email </b></td>
                    <td>
                        @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                        @ViewData["Loi2"]
                        @ViewData["Loi2e"]
                    </td>
                </tr>
                <tr>
                    <td style="width:125px"><b>Số điện thoại </b></td>
                    <td>
                        @Html.TextBoxFor(model => model.Phone, new { @class = "form-control" })
                        @ViewData["Loi3"]
                        @ViewData["Loi3e"]
                    </td>
                </tr>
            </table>
        </div>
        <p>
            <input type="submit" value="Lưu cập nhật" class="btn btn-success" />
        </p>
    </fieldset>
}
<div>
    @Html.ActionLink("Trở lại", "users", "adminmanager")
</div>